//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projektverwaltung.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aktivitaet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Aktivitaet()
        {
            this.AktivitaetMitarbeiter = new HashSet<AktivitaetMitarbeiter>();
            this.Dokument = new HashSet<Dokument>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> status { get; set; }
        public int projektphase_id { get; set; }
        public Nullable<System.DateTime> startdatum_geplant { get; set; }
        public Nullable<System.DateTime> enddatum_geplant { get; set; }
        public Nullable<System.DateTime> startdatum_effektiv { get; set; }
        public Nullable<System.DateTime> enddatum_effektiv { get; set; }
        public Nullable<double> erwartete_kosten { get; set; }
        public Nullable<double> effektive_kosten { get; set; }
        public int kostenart_id { get; set; }
        public Nullable<double> fortschritt { get; set; }
        public string dokumente_link { get; set; }
    
        public virtual Kostenart Kostenart { get; set; }
        public virtual ProjektPhase ProjektPhase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AktivitaetMitarbeiter> AktivitaetMitarbeiter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dokument> Dokument { get; set; }
    }
}
