//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projektverwaltung.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dokument
    {
        public int id { get; set; }
        public Nullable<int> projekt_id { get; set; }
        public Nullable<int> projektphase_id { get; set; }
        public Nullable<int> aktivitaet_id { get; set; }
        public string pfad { get; set; }
    
        public virtual Aktivitaet Aktivitaet { get; set; }
        public virtual Projekt Projekt { get; set; }
        public virtual ProjektPhase ProjektPhase { get; set; }
    }
}
