//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projektverwaltung.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projekt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Projekt()
        {
            this.Dokument = new HashSet<Dokument>();
            this.ProjektPhase = new HashSet<ProjektPhase>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string beschreibung { get; set; }
        public int status { get; set; }
        public int prioritaet { get; set; }
        public System.DateTime startdatum_geplant { get; set; }
        public System.DateTime enddatum_geplant { get; set; }
        public Nullable<System.DateTime> startdatum_effektiv { get; set; }
        public Nullable<System.DateTime> enddatum_effektiv { get; set; }
        public Nullable<double> fortschritt { get; set; }
        public string dokument_link { get; set; }
        public int projektleiter_id { get; set; }
        public int vorgehensmodell_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dokument> Dokument { get; set; }
        public virtual Mitarbeiter Mitarbeiter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjektPhase> ProjektPhase { get; set; }
        public virtual Vorgehensmodell Vorgehensmodell { get; set; }
    }
}
