//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projektverwaltung.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjektverwaltungEntities : DbContext
    {
        public ProjektverwaltungEntities()
            : base("name=ProjektverwaltungEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aktivitaet> Aktivitaet { get; set; }
        public virtual DbSet<AktivitaetMitarbeiter> AktivitaetMitarbeiter { get; set; }
        public virtual DbSet<Dokument> Dokument { get; set; }
        public virtual DbSet<Funktion> Funktion { get; set; }
        public virtual DbSet<Kostenart> Kostenart { get; set; }
        public virtual DbSet<Meilenstein> Meilenstein { get; set; }
        public virtual DbSet<Mitarbeiter> Mitarbeiter { get; set; }
        public virtual DbSet<MitarbeiterFunktion> MitarbeiterFunktion { get; set; }
        public virtual DbSet<Projekt> Projekt { get; set; }
        public virtual DbSet<ProjektPhase> ProjektPhase { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Vorgehensmodell> Vorgehensmodell { get; set; }
        public virtual DbSet<VorgehensmodellPhase> VorgehensmodellPhase { get; set; }
    }
}
